name: Build and Deploy FortiSafe

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Build and push Frontend Docker image
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fortisafe-frontend:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
      
      # Build and push Backend Docker image
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fortisafe-backend:latest
          build-args: |
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
            AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
            AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
            AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}
            AUTH0_CALLBACK_URL=${{ secrets.AUTH0_CALLBACK_URL }}
            PORT=${{ secrets.PORT }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            EXTENSION_URL=${{ secrets.EXTENSION_URL }}
            PASSWORD_ENCRYPTION_KEY=${{ secrets.PASSWORD_ENCRYPTION_KEY }}
            GOOGLE_SAFE_BROWSING_API_KEY=${{ secrets.GOOGLE_SAFE_BROWSING_API_KEY }}
            BREVO_SMTP=${{ secrets.BREVO_SMTP }}
            BREVO_SMTP_PORT=${{ secrets.BREVO_SMTP_PORT }}
            BREVO_USER=${{ secrets.BREVO_USER }}
            BREVO_PASS=${{ secrets.BREVO_PASS }}
            EMAIL_FROM_ADDRESS=${{ secrets.EMAIL_FROM_ADDRESS }}
            BREVO_BASE_URL=${{ secrets.BREVO_BASE_URL }}
            EMAIL_FROM_NAME=${{ secrets.EMAIL_FROM_NAME }}
            BREVO_API_URL=${{ secrets.BREVO_API_URL }}
      
      # Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Login to Docker Hub
            echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            # Create docker-compose.yml if it doesn't exist
            cat > ~/docker-compose.yml << 'EOL'
            version: '3.8'
            
            services:
              frontend:
                image: ${{ secrets.DOCKER_USERNAME }}/fortisafe-frontend:latest
                container_name: fortisafe-frontend
                restart: always
                ports:
                  - "3000:3000"
                environment:
                  - NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
            
              backend:
                image: ${{ secrets.DOCKER_USERNAME }}/fortisafe-backend:latest
                container_name: fortisafe-backend
                restart: always
                ports:
                  - "8080:8080"
                environment:
                  - MONGODB_URI=${{ secrets.MONGODB_URI }}
                  - AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
                  - AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
                  - AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
                  - AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}
                  - AUTH0_CALLBACK_URL=${{ secrets.AUTH0_CALLBACK_URL }}
                  - PORT=${{ secrets.PORT }}
                  - FRONTEND_URL=${{ secrets.FRONTEND_URL }}
                  - EXTENSION_URL=${{ secrets.EXTENSION_URL }}
                  - PASSWORD_ENCRYPTION_KEY=${{ secrets.PASSWORD_ENCRYPTION_KEY }}
                  - GOOGLE_SAFE_BROWSING_API_KEY=${{ secrets.GOOGLE_SAFE_BROWSING_API_KEY }}
                  - BREVO_SMTP=${{ secrets.BREVO_SMTP }}
                  - BREVO_SMTP_PORT=${{ secrets.BREVO_SMTP_PORT }}
                  - BREVO_USER=${{ secrets.BREVO_USER }}
                  - BREVO_PASS=${{ secrets.BREVO_PASS }}
                  - EMAIL_FROM_ADDRESS=${{ secrets.EMAIL_FROM_ADDRESS }}
                  - BREVO_BASE_URL=${{ secrets.BREVO_BASE_URL }}
                  - EMAIL_FROM_NAME=${{ secrets.EMAIL_FROM_NAME }}
                  - BREVO_API_URL=${{ secrets.BREVO_API_URL }}
            EOL
            
            # Pull the latest images
            docker-compose pull
            
            # Stop and remove existing containers
            docker-compose down
            
            # Start the new containers
            docker-compose up -d
            
            # Cleanup unused images
            docker image prune -af
